### ISSUE TITLE
Secure key-exchange application

### ISSUE THREAD

**Issue by jverbraeken** [ericcornelissen/NervousFish#1]
As a user I want to have an app to securely exchange keys so that I can be sure I have the correct key

* * *

__Subtasks:__
- [x] As a user I want to be able to pair devices using Bluetooth to exchange data (#2)
  - [ ] As a user I want to make a Bluetooth connection with an extra security layer so that I can be sure that a certain connection is with the person I chose to make a connection with. #61 
- [x] As a user I want to make connections with other users with alternatives to Bluetooth so that I can use the option I like. #62 #8 #9 
  - [x] As a user I want to make connections with other users through NFC so that I can receive their public key in an alternative manner. #8 
  - [x] As a user I want to receive a public key of a person by scanning a QR code from his screen so that I can receive their public key without making a real connection. #62 #9 
- [x] As a user I want to have a screen with a list of names of the people of whom I have a public key so I can see my contacts. #10 
  - [x] As a user I want to be able to change the name of a contact so I can always tell who they are. #11 
  - [x] As a user I want to be able to delete someone from my contacts because they're key is no longer valid (or other reasons). #12 
  - [x] As a user I want to be able to sort my contacts based on their name and date added so that I can easily find a specific person. #13 
- [x] As a user I want to be able to see the public key of all my contacts so they (the keys) can be used manually in other applications. #62 
- [x] As a user I want to be able to share my keys with other devices so that other who trust me can get more keys. #15 
- [x] As a user I want to be able to export the list with contacts together with their keys so that I can later import them on another phone. #63
